### ISSUE TITLE
labeled speed doesnt match current game speed

### ISSUE THREAD

**Issue by merlinmadhat** [sgjsakura/AOE2DE-Localization#3]
Is it possible to get the labels/tooltips to show the correct creation time if the game is on fast speed?
Also creating a "pull request" doesn't seem to work.

**Comment by sgjsakura** [comment]
Hi, thank you for your response. Unfortunately, this mod is implemented by replacing the string resources in the game resource file. All these messages are static with only few exceptions on resource cost, and unit basic data (attack and armors, etc.). The game engine currently does not support to set dynamic text on all of extended data items provided by this game, and thus it is impossible to change the value according to the game speed/user civilization bonus/team bonus or any other game run-time information.

I've made a post on AOE official forum to request the development team support more dynamic data in the text, however I know this will lead to a major change in the game engine and it is difficult, and currently the development team has no reply for this request yet.

For pull request problem, it's provided by Github and I have not made any special setting for this problem, so please refer to Github help documentation for this feature and if you have any question you may contact the Github support for help.

I'm closing this issue and please feel free to reopen it if you have any new problem.
