### ISSUE TITLE
数据bug

### ISSUE THREAD

**Issue by copytac** [sgjsakura/AOE2DE-Localization#5]
翼骑兵的攻击间隔比轻骑兵小，hd为1.9，城堡副箭与主箭攻击力相同均为11。另外，在兵种升级的资源消耗后加上时间消耗就更好了。

**Comment by sgjsakura** [comment]
hi，前辈你好，感谢你的反馈，目前版本的数据中确实有少部分有误，我们会尽快更新错误的数据~

如果有其他问题欢迎继续留言~
